"""add last_session_time to attendance_reports

Revision ID: 01fb4d68c2d1
Revises: 720fff6aa213
Create Date: 2026-04-05 00:54:04.124299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01fb4d68c2d1'
down_revision: Union[str, Sequence[str], None] = '720fff6aa213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_report_details')
    op.add_column('attendance_reports', sa.Column('last_session_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendances', sa.Column('face_image_path', sa.String(), nullable=True))
    op.add_column('attendances', sa.Column('reverify_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendances', sa.Column('reverify_image_path', sa.String(), nullable=True))
    op.add_column('class_students', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('classes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('class_students', 'joined_at')
    op.drop_column('attendances', 'reverify_image_path')
    op.drop_column('attendances', 'reverify_time')
    op.drop_column('attendances', 'face_image_path')
    op.drop_column('attendance_reports', 'last_session_time')
    op.create_table('attendance_report_details',
    sa.Column('detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Present', 'Late', 'Absent', 'LeftEarly', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('is_reverified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['attendance_reports.report_id'], name=op.f('attendance_report_details_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], name=op.f('attendance_report_details_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('attendance_report_details_pkey'))
    )
    # ### end Alembic commands ###
