"""empty message

Revision ID: 02714f9d856f
Revises: 19ed03e04a16
Create Date: 2025-09-23 16:20:57.420157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02714f9d856f'
down_revision: Union[str, Sequence[str], None] = '19ed03e04a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_face_samples', sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_face_samples', 'face_embedding')
    # ### end Alembic commands ###
