"""add unique constraint for user face sample

Revision ID: 0630d0327c24
Revises: 02714f9d856f
Create Date: 2025-09-30 20:17:02.654609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0630d0327c24'
down_revision: Union[str, Sequence[str], None] = '02714f9d856f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_face_sample_user', 'user_face_samples', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_face_sample_user', 'user_face_samples', type_='unique')
    # ### end Alembic commands ###
