"""add_announce_ment

Revision ID: 0d6812c37776
Revises: 06d8ab98d199
Create Date: 2025-11-05 02:29:43.793703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6812c37776'
down_revision: Union[str, Sequence[str], None] = '06d8ab98d199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cw_submissions_assignment'), table_name='classwork_submissions')
    op.drop_index(op.f('ix_cw_submissions_student'), table_name='classwork_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cw_submissions_student'), 'classwork_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_cw_submissions_assignment'), 'classwork_submissions', ['assignment_id'], unique=False)
    # ### end Alembic commands ###
