"""ชื่อรายละเอียดการแก้ไข

Revision ID: 11809c886c7c
Revises: 09a377113c31
Create Date: 2026-05-13 19:09:13.180821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11809c886c7c'
down_revision: Union[str, Sequence[str], None] = '09a377113c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
