"""Create ChatMessage table

Revision ID: 35355f072f24
Revises: f21cbc8a8924
Create Date: 2026-06-29 17:15:30.876269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35355f072f24'
down_revision: Union[str, Sequence[str], None] = 'f21cbc8a8924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'class_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'class_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
