"""add attendance_reports table

Revision ID: 3816869da5a7
Revises: 1a35f96aa3a2
Create Date: 2025-11-05 05:54:36.130826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3816869da5a7'
down_revision: Union[str, Sequence[str], None] = '1a35f96aa3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_class_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_teacher_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('announcement_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pinned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('announcements_class_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name=op.f('announcements_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('announcement_id', name=op.f('announcements_pkey'))
    )
    op.create_index(op.f('ix_announcements_teacher_id'), 'announcements', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_announcements_class_id'), 'announcements', ['class_id'], unique=False)
    # ### end Alembic commands ###
