"""empty message

Revision ID: 3de5c849e7de
Revises: b34b60b93fb1
Create Date: 2026-04-15 00:40:17.965193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de5c849e7de'
down_revision: Union[str, Sequence[str], None] = 'b34b60b93fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_report_details')
    op.add_column('attendance_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_sessions', 'is_active')
    op.create_table('attendance_report_details',
    sa.Column('detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Present', 'Late', 'Absent', 'LeftEarly', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('is_reverified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('face_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reverify_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reverify_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['attendance_reports.report_id'], name=op.f('attendance_report_details_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], name=op.f('attendance_report_details_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('attendance_report_details_pkey'))
    )
    # ### end Alembic commands ###
