"""reverify

Revision ID: 4d5e148aebcf
Revises: a76a3b6aac02
Create Date: 2025-11-01 02:40:19.090607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d5e148aebcf'
down_revision: Union[str, Sequence[str], None] = 'a76a3b6aac02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('reverify_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('reverify_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('gps_required_before_end_minutes', sa.Integer(), nullable=True))
    op.alter_column('attendance_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('attendance_sessions', 'gps_required_before_end_minutes')
    op.drop_column('attendance_sessions', 'reverify_deadline')
    op.drop_column('attendance_sessions', 'reverify_time')
    # ### end Alembic commands ###
