"""add_is_manual_override_to_report_detail

Revision ID: 5a45b8179022
Revises: e0ca59b46b57
Create Date: 2026-05-15 22:09:49.759171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a45b8179022'
down_revision: Union[str, Sequence[str], None] = 'e0ca59b46b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('attendance_report_details', sa.Column('is_manual_override', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE attendance_report_details SET is_manual_override = False")
    
    # 3. Change to non-nullable
    op.alter_column('attendance_report_details', 'is_manual_override', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_report_details', 'is_manual_override')
    # ### end Alembic commands ###
