"""fix teacher_locations PK

Revision ID: 5f441f9eeeac
Revises: 9aabbc8f432f
Create Date: 2025-10-05 22:39:16.711761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f441f9eeeac'
down_revision: Union[str, Sequence[str], None] = '9aabbc8f432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
