"""empty message

Revision ID: 6193e79e8868
Revises: 68424341f1de
Create Date: 2025-11-04 01:37:29.586750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6193e79e8868'
down_revision: Union[str, Sequence[str], None] = '68424341f1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classwork',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content_url', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
    'submission_status',
    sa.dialects.postgresql.ENUM(
        'On_Time', 'Late', 'Not_Submitted',
        name='submissionlateness',
        create_type=False
    ),
    nullable=False,
    server_default='Not_Submitted',
 ),

    sa.Column('graded', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('class_id', 'student_id', 'title', name='uq_classwork_submission')
    )
    op.create_index('ix_classwork_class_student', 'classwork', ['class_id', 'student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classwork_class_student', table_name='classwork')
    op.drop_table('classwork')
    # ### end Alembic commands ###
