"""merge guy

Revision ID: 720fff6aa213
Revises: a45dcd30c871
Create Date: 2026-03-27 17:23:12.581258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "720fff6aa213"
down_revision: Union[str, Sequence[str], None] = "a45dcd30c871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. ลบตารางที่ไม่ใช้แล้วออก
    op.drop_table("attendance_report_details")

    # 2. เพิ่ม column is_archived พร้อมกำหนดค่าเริ่มต้นเป็น false สำหรับข้อมูลเก่า
    op.add_column(
        "classes",
        sa.Column("is_archived", sa.Boolean(), nullable=False, server_default="false"),
    )

    # 3. สร้าง Index
    op.create_index(
        op.f("ix_classes_is_archived"), "classes", ["is_archived"], unique=False
    )

    # 4. เพิ่ม column updated_at (แบบยอมให้เป็น null ได้)
    op.add_column(
        "user_face_samples", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_face_samples", "updated_at")
    op.drop_index(op.f("ix_classes_is_archived"), table_name="classes")
    op.drop_column("classes", "is_archived")

    op.create_table(
        "attendance_report_details",
        sa.Column("detail_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("report_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "check_in_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Present", "Late", "Absent", "LeftEarly", name="reportstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_reverified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("face_image_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "session_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "reverify_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "reverify_image_path", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["attendance_reports.report_id"],
            name=op.f("attendance_report_details_report_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.session_id"],
            name=op.f("attendance_report_details_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "detail_id", name=op.f("attendance_report_details_pkey")
        ),
    )
    # ### end Alembic commands ###
