"""update name columns teachr_lo and student_lo

Revision ID: 9aabbc8f432f
Revises: dcccb3ce99a4
Create Date: 2025-10-05 20:48:53.365051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aabbc8f432f'
down_revision: Union[str, Sequence[str], None] = 'dcccb3ce99a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_locations', sa.Column('student_location_id', sa.UUID(), nullable=False))
    op.drop_column('student_locations', 'log_id')
    op.add_column('teacher_locations', sa.Column('teacher_location_id', sa.UUID(), nullable=False))
    op.drop_column('teacher_locations', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_locations', sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('teacher_locations', 'teacher_location_id')
    op.add_column('student_locations', sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('student_locations', 'student_location_id')
    # ### end Alembic commands ###
