"""add reverify_enabled to attendance_sessions

Revision ID: 9af884313de9
Revises: f0d8e07748ba
Create Date: 2025-11-03 03:43:38.944961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af884313de9'
down_revision: Union[str, Sequence[str], None] = 'f0d8e07748ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
