"""Add code column to classes table

Revision ID: 9e71f131437a
Revises: 0630d0327c24
Create Date: 2025-10-02 17:39:49.764102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e71f131437a'
down_revision: Union[str, Sequence[str], None] = '0630d0327c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'classes', ['code'])
    op.drop_constraint(op.f('uq_user_face_sample_user'), 'user_face_samples', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_face_sample_user'), 'user_face_samples', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'classes', type_='unique')
    op.drop_column('classes', 'code')
    # ### end Alembic commands ###
