"""add_last_session_time_to_report

Revision ID: a45dcd30c871
Revises: e526d60e2890
Create Date: 2026-03-27 14:02:12.675858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a45dcd30c871'
down_revision: Union[str, Sequence[str], None] = 'e526d60e2890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_report_details')
    op.add_column('attendance_reports', sa.Column('last_session_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_reports', 'last_session_time')
    op.create_table('attendance_report_details',
    sa.Column('detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Present', 'Late', 'Absent', 'LeftEarly', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('is_reverified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('face_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reverify_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reverify_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['attendance_reports.report_id'], name=op.f('attendance_report_details_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], name=op.f('attendance_report_details_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('attendance_report_details_pkey'))
    )
    # ### end Alembic commands ###
