"""update table classes name not unique

Revision ID: a52fb3a0ea9a
Revises: 9e71f131437a
Create Date: 2025-10-02 18:47:45.319505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52fb3a0ea9a'
down_revision: Union[str, Sequence[str], None] = '9e71f131437a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    # ### end Alembic commands ###
