"""fix teacher_locations PK

Revision ID: a980045c6f04
Revises: 5f441f9eeeac
Create Date: 2025-10-05 22:51:42.830279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a980045c6f04'
down_revision: Union[str, Sequence[str], None] = '5f441f9eeeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_locations', sa.Column('stdl_id', sa.UUID(), nullable=False))
    op.drop_column('student_locations', 'student_location_id')
    op.add_column('teacher_locations', sa.Column('tl_id', sa.UUID(), nullable=False))
    op.drop_column('teacher_locations', 'teacher_location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_locations', sa.Column('teacher_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('teacher_locations', 'tl_id')
    op.add_column('student_locations', sa.Column('student_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('student_locations', 'stdl_id')
    # ### end Alembic commands ###
