"""add_is_silent_check_to_student_location

Revision ID: b34b60b93fb1
Revises: ad1ccf0cc01a
Create Date: 2026-04-10 18:01:28.227952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34b60b93fb1'
down_revision: Union[str, Sequence[str], None] = 'ad1ccf0cc01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_locations', sa.Column('is_silent_check', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_locations', 'is_silent_check')
    # ### end Alembic commands ###
