"""RealTime

Revision ID: b8d51a2dba41
Revises: 5a45b8179022
Create Date: 2026-05-17 19:58:05.416303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d51a2dba41'
down_revision: Union[str, Sequence[str], None] = '5a45b8179022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.announcement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index('ix_announcement_attachments_announcement', 'announcement_attachments', ['announcement_id'], unique=False)
    op.add_column('attendance_report_details', sa.Column('is_manual_override', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('attendances', sa.Column('is_manual_override', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'is_manual_override')
    op.drop_column('attendance_report_details', 'is_manual_override')
    op.drop_index('ix_announcement_attachments_announcement', table_name='announcement_attachments')
    op.drop_table('announcement_attachments')
    # ### end Alembic commands ###
