"""Add code column to classes table

Revision ID: dcccb3ce99a4
Revises: f6f8f8ae685d
Create Date: 2025-10-05 20:38:04.037529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcccb3ce99a4'
down_revision: Union[str, Sequence[str], None] = 'f6f8f8ae685d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('recorded_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'users', ['recorded_by_user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'recorded_by_user_id')
    # ### end Alembic commands ###
