"""add_is_manual_override_to_attendance

Revision ID: e0ca59b46b57
Revises: 2e2f14ce6883
Create Date: 2026-05-15 21:27:53.255800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ca59b46b57'
down_revision: Union[str, Sequence[str], None] = '2e2f14ce6883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('attendances', sa.Column('is_manual_override', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE attendances SET is_manual_override = False")
    
    # 3. Change to non-nullable
    op.alter_column('attendances', 'is_manual_override', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'is_manual_override')
    # ### end Alembic commands ###
