"""add_joined_at_to_class_students

Revision ID: eb175e9f2f6a
Revises: d830fde76f1e
Create Date: 2026-03-25 18:23:04.585908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb175e9f2f6a'
down_revision: Union[str, Sequence[str], None] = 'd830fde76f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_report_details')
    op.drop_column('attendances', 'is_reverify_required')
    op.drop_column('attendances', 'left_early_reason')
    op.drop_column('attendances', 'reverify_deadline_at')
    op.drop_column('attendances', 'is_manual_override')
    op.drop_column('attendances', 'reverify_requested_at')
    op.add_column('class_students', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('otps_user_id_fkey'), 'otps', type_='foreignkey')
    op.create_foreign_key(None, 'otps', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.create_foreign_key(op.f('otps_user_id_fkey'), 'otps', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('class_students', 'joined_at')
    op.add_column('attendances', sa.Column('reverify_requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('is_manual_override', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('reverify_deadline_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('left_early_reason', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('is_reverify_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('attendance_report_details',
    sa.Column('detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Present', 'Late', 'Absent', 'LeftEarly', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('is_reverified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['attendance_reports.report_id'], name=op.f('attendance_report_details_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], name=op.f('attendance_report_details_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('attendance_report_details_pkey'))
    )
    # ### end Alembic commands ###
