"""auto update models to latest schema

Revision ID: ecbdfbea09a3
Revises: 128498c5823a
Create Date: 2025-10-14 20:38:42.303017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecbdfbea09a3'
down_revision: Union[str, Sequence[str], None] = '128498c5823a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance_sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_attendance_sessions_active'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_column('attendance_sessions', 'created_at')
    op.drop_column('attendance_sessions', 'is_active')
    op.drop_index(op.f('ix_attendances_session_id'), table_name='attendances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendances_session_id'), 'attendances', ['session_id'], unique=False)
    op.add_column('attendance_sessions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('attendance_sessions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_class_id'), 'attendance_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_active'), 'attendance_sessions', ['is_active'], unique=False)
    op.alter_column('attendance_sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('attendance_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
