"""add reverify_enabled to attendance_sessions

Revision ID: f0d8e07748ba
Revises: 4d5e148aebcf
Create Date: 2025-11-03 03:43:18.685773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d8e07748ba'
down_revision: Union[str, Sequence[str], None] = '4d5e148aebcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('reverify_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('attendance_sessions', 'reverify_deadline')
    op.drop_column('attendance_sessions', 'reverify_time')
    op.drop_column('attendance_sessions', 'gps_required_before_end_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('gps_required_before_end_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance_sessions', sa.Column('reverify_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('attendance_sessions', sa.Column('reverify_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('attendance_sessions', 'reverify_enabled')
    # ### end Alembic commands ###
