"""Add core attendance and location tracking tables

Revision ID: f6f8f8ae685d
Revises: a52fb3a0ea9a
Create Date: 2025-10-04 20:34:39.383450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f8f8ae685d'
down_revision: Union[str, Sequence[str], None] = 'a52fb3a0ea9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.create_unique_constraint('uq_user_face_sample_user', 'user_face_samples', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_face_sample_user', 'user_face_samples', type_='unique')
    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_manual_override', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('attendance_class_id_fkey')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.user_id'], name=op.f('attendance_recorded_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name=op.f('attendance_student_id_fkey')),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('attendance_pkey'))
    )
    # ### end Alembic commands ###
