"""Update ChatMessage relations

Revision ID: fa474d1fc5a8
Revises: f2c9d4a1b8e7
Create Date: 2026-06-29 15:24:55.698988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa474d1fc5a8'
down_revision: Union[str, Sequence[str], None] = 'f2c9d4a1b8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
