// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMMzzgFxQ1FV5klDLjSFDZUgwtTCFIhjM',
    appId: '1:41456060432:web:72999f13e7dad49f306295',
    messagingSenderId: '41456060432',
    projectId: 'fastcheck-5fd70',
    authDomain: 'fastcheck-5fd70.firebaseapp.com',
    storageBucket: 'fastcheck-5fd70.firebasestorage.app',
    measurementId: 'G-7N7HNHCZJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArp6Y65WTM3NjnGyrHLGo_IWl5hNkMBSE',
    appId: '1:41456060432:android:d67b8dd951019d20306295',
    messagingSenderId: '41456060432',
    projectId: 'fastcheck-5fd70',
    storageBucket: 'fastcheck-5fd70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9fKdlIop_-E6OFMHoTKUVkfkJEJHxNg',
    appId: '1:41456060432:ios:5196895ed1f1d3b4306295',
    messagingSenderId: '41456060432',
    projectId: 'fastcheck-5fd70',
    storageBucket: 'fastcheck-5fd70.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9fKdlIop_-E6OFMHoTKUVkfkJEJHxNg',
    appId: '1:41456060432:ios:5196895ed1f1d3b4306295',
    messagingSenderId: '41456060432',
    projectId: 'fastcheck-5fd70',
    storageBucket: 'fastcheck-5fd70.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMMzzgFxQ1FV5klDLjSFDZUgwtTCFIhjM',
    appId: '1:41456060432:web:28e99aacf16b5d89306295',
    messagingSenderId: '41456060432',
    projectId: 'fastcheck-5fd70',
    authDomain: 'fastcheck-5fd70.firebaseapp.com',
    storageBucket: 'fastcheck-5fd70.firebasestorage.app',
    measurementId: 'G-LLYN40NRZ0',
  );
}
