// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqiBW3hmzSTl5xOynK2ve3q_VWiV75kbA',
    appId: '1:15265354217:web:4aeadc26f18dc809ba7b78',
    messagingSenderId: '15265354217',
    projectId: 'fastcheck-efddd',
    authDomain: 'fastcheck-efddd.firebaseapp.com',
    storageBucket: 'fastcheck-efddd.firebasestorage.app',
    measurementId: 'G-7ZBD5NZ4CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDul1uf_EyWsbZbQa66SHcA3eaqMmALKJ4',
    appId: '1:15265354217:android:881b673bc9677ffeba7b78',
    messagingSenderId: '15265354217',
    projectId: 'fastcheck-efddd',
    storageBucket: 'fastcheck-efddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIMMOWb1-Gdpj1p0qMCPkR0iG2wJnKMA',
    appId: '1:15265354217:ios:63c4c4c0d0f451dbba7b78',
    messagingSenderId: '15265354217',
    projectId: 'fastcheck-efddd',
    storageBucket: 'fastcheck-efddd.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJIMMOWb1-Gdpj1p0qMCPkR0iG2wJnKMA',
    appId: '1:15265354217:ios:63c4c4c0d0f451dbba7b78',
    messagingSenderId: '15265354217',
    projectId: 'fastcheck-efddd',
    storageBucket: 'fastcheck-efddd.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqiBW3hmzSTl5xOynK2ve3q_VWiV75kbA',
    appId: '1:15265354217:web:76632c2ac063e24cba7b78',
    messagingSenderId: '15265354217',
    projectId: 'fastcheck-efddd',
    authDomain: 'fastcheck-efddd.firebaseapp.com',
    storageBucket: 'fastcheck-efddd.firebasestorage.app',
    measurementId: 'G-S79ZTHEDV7',
  );
}
